---
name: Submodule Updates

on:
  push

jobs:
  build:
    name: Submodule update
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: run action
        id: run_action
        uses: PaulRitter/github-action-create-commit-parent-submodule@v2.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          parent_repository: camillegiuliano/TestParent
          parent_branch: main